(cl:defpackage ArmController-srv
  (:use )
  (:export
   "GETMOTORANGLE"
   "<GETMOTORANGLE-REQUEST>"
   "GETMOTORANGLE-REQUEST"
   "<GETMOTORANGLE-RESPONSE>"
   "GETMOTORANGLE-RESPONSE"
   "MOVERELATIVETOOL"
   "<MOVERELATIVETOOL-REQUEST>"
   "MOVERELATIVETOOL-REQUEST"
   "<MOVERELATIVETOOL-RESPONSE>"
   "MOVERELATIVETOOL-RESPONSE"
   "GETARMSTATUS"
   "<GETARMSTATUS-REQUEST>"
   "GETARMSTATUS-REQUEST"
   "<GETARMSTATUS-RESPONSE>"
   "GETARMSTATUS-RESPONSE"
   "MOVEABSOLUTEMOTOR"
   "<MOVEABSOLUTEMOTOR-REQUEST>"
   "MOVEABSOLUTEMOTOR-REQUEST"
   "<MOVEABSOLUTEMOTOR-RESPONSE>"
   "MOVEABSOLUTEMOTOR-RESPONSE"
  ))

