// Generated by gencpp from file ArmController/GetArmStatusResponse.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_GETARMSTATUSRESPONSE_H
#define ARMCONTROLLER_MESSAGE_GETARMSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ArmController
{
template <class ContainerAllocator>
struct GetArmStatusResponse_
{
  typedef GetArmStatusResponse_<ContainerAllocator> Type;

  GetArmStatusResponse_()
    : status(0)  {
    }
  GetArmStatusResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
    }



   typedef int8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::ArmController::GetArmStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ArmController::GetArmStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetArmStatusResponse_

typedef ::ArmController::GetArmStatusResponse_<std::allocator<void> > GetArmStatusResponse;

typedef boost::shared_ptr< ::ArmController::GetArmStatusResponse > GetArmStatusResponsePtr;
typedef boost::shared_ptr< ::ArmController::GetArmStatusResponse const> GetArmStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ArmController::GetArmStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ArmController

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::GetArmStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::GetArmStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::GetArmStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::ArmController::GetArmStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmController/GetArmStatusResponse";
  }

  static const char* value(const ::ArmController::GetArmStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n\
\n\
";
  }

  static const char* value(const ::ArmController::GetArmStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetArmStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ArmController::GetArmStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ArmController::GetArmStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_GETARMSTATUSRESPONSE_H
