// Generated by gencpp from file ArmController/GetArmStatus.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_GETARMSTATUS_H
#define ARMCONTROLLER_MESSAGE_GETARMSTATUS_H

#include <ros/service_traits.h>


#include <ArmController/GetArmStatusRequest.h>
#include <ArmController/GetArmStatusResponse.h>


namespace ArmController
{

struct GetArmStatus
{

typedef GetArmStatusRequest Request;
typedef GetArmStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetArmStatus
} // namespace ArmController


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ArmController::GetArmStatus > {
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::ArmController::GetArmStatus&) { return value(); }
};

template<>
struct DataType< ::ArmController::GetArmStatus > {
  static const char* value()
  {
    return "ArmController/GetArmStatus";
  }

  static const char* value(const ::ArmController::GetArmStatus&) { return value(); }
};


// service_traits::MD5Sum< ::ArmController::GetArmStatusRequest> should match 
// service_traits::MD5Sum< ::ArmController::GetArmStatus > 
template<>
struct MD5Sum< ::ArmController::GetArmStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::GetArmStatus >::value();
  }
  static const char* value(const ::ArmController::GetArmStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::GetArmStatusRequest> should match 
// service_traits::DataType< ::ArmController::GetArmStatus > 
template<>
struct DataType< ::ArmController::GetArmStatusRequest>
{
  static const char* value()
  {
    return DataType< ::ArmController::GetArmStatus >::value();
  }
  static const char* value(const ::ArmController::GetArmStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ArmController::GetArmStatusResponse> should match 
// service_traits::MD5Sum< ::ArmController::GetArmStatus > 
template<>
struct MD5Sum< ::ArmController::GetArmStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::GetArmStatus >::value();
  }
  static const char* value(const ::ArmController::GetArmStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::GetArmStatusResponse> should match 
// service_traits::DataType< ::ArmController::GetArmStatus > 
template<>
struct DataType< ::ArmController::GetArmStatusResponse>
{
  static const char* value()
  {
    return DataType< ::ArmController::GetArmStatus >::value();
  }
  static const char* value(const ::ArmController::GetArmStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_GETARMSTATUS_H
