// Generated by gencpp from file ArmController/GetMotorAngle.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_GETMOTORANGLE_H
#define ARMCONTROLLER_MESSAGE_GETMOTORANGLE_H

#include <ros/service_traits.h>


#include <ArmController/GetMotorAngleRequest.h>
#include <ArmController/GetMotorAngleResponse.h>


namespace ArmController
{

struct GetMotorAngle
{

typedef GetMotorAngleRequest Request;
typedef GetMotorAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMotorAngle
} // namespace ArmController


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ArmController::GetMotorAngle > {
  static const char* value()
  {
    return "fb28cd0b4dec57104328493f86235b1b";
  }

  static const char* value(const ::ArmController::GetMotorAngle&) { return value(); }
};

template<>
struct DataType< ::ArmController::GetMotorAngle > {
  static const char* value()
  {
    return "ArmController/GetMotorAngle";
  }

  static const char* value(const ::ArmController::GetMotorAngle&) { return value(); }
};


// service_traits::MD5Sum< ::ArmController::GetMotorAngleRequest> should match 
// service_traits::MD5Sum< ::ArmController::GetMotorAngle > 
template<>
struct MD5Sum< ::ArmController::GetMotorAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::GetMotorAngle >::value();
  }
  static const char* value(const ::ArmController::GetMotorAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::GetMotorAngleRequest> should match 
// service_traits::DataType< ::ArmController::GetMotorAngle > 
template<>
struct DataType< ::ArmController::GetMotorAngleRequest>
{
  static const char* value()
  {
    return DataType< ::ArmController::GetMotorAngle >::value();
  }
  static const char* value(const ::ArmController::GetMotorAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ArmController::GetMotorAngleResponse> should match 
// service_traits::MD5Sum< ::ArmController::GetMotorAngle > 
template<>
struct MD5Sum< ::ArmController::GetMotorAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::GetMotorAngle >::value();
  }
  static const char* value(const ::ArmController::GetMotorAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::GetMotorAngleResponse> should match 
// service_traits::DataType< ::ArmController::GetMotorAngle > 
template<>
struct DataType< ::ArmController::GetMotorAngleResponse>
{
  static const char* value()
  {
    return DataType< ::ArmController::GetMotorAngle >::value();
  }
  static const char* value(const ::ArmController::GetMotorAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_GETMOTORANGLE_H
