// Generated by gencpp from file ArmController/GetMotorAngleResponse.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_GETMOTORANGLERESPONSE_H
#define ARMCONTROLLER_MESSAGE_GETMOTORANGLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ArmController
{
template <class ContainerAllocator>
struct GetMotorAngleResponse_
{
  typedef GetMotorAngleResponse_<ContainerAllocator> Type;

  GetMotorAngleResponse_()
    : angle(0.0)  {
    }
  GetMotorAngleResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
    }



   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMotorAngleResponse_

typedef ::ArmController::GetMotorAngleResponse_<std::allocator<void> > GetMotorAngleResponse;

typedef boost::shared_ptr< ::ArmController::GetMotorAngleResponse > GetMotorAngleResponsePtr;
typedef boost::shared_ptr< ::ArmController::GetMotorAngleResponse const> GetMotorAngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ArmController::GetMotorAngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ArmController

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::ArmController::GetMotorAngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmController/GetMotorAngleResponse";
  }

  static const char* value(const ::ArmController::GetMotorAngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
\n\
";
  }

  static const char* value(const ::ArmController::GetMotorAngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetMotorAngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ArmController::GetMotorAngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ArmController::GetMotorAngleResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_GETMOTORANGLERESPONSE_H
