// Generated by gencpp from file ArmController/MoveRelativeToolRequest.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_MOVERELATIVETOOLREQUEST_H
#define ARMCONTROLLER_MESSAGE_MOVERELATIVETOOLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ArmController
{
template <class ContainerAllocator>
struct MoveRelativeToolRequest_
{
  typedef MoveRelativeToolRequest_<ContainerAllocator> Type;

  MoveRelativeToolRequest_()
    : tx(0)
    , ty(0)
    , tz(0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  MoveRelativeToolRequest_(const ContainerAllocator& _alloc)
    : tx(0)
    , ty(0)
    , tz(0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }



   typedef int32_t _tx_type;
  _tx_type tx;

   typedef int32_t _ty_type;
  _ty_type ty;

   typedef int32_t _tz_type;
  _tz_type tz;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;




  typedef boost::shared_ptr< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRelativeToolRequest_

typedef ::ArmController::MoveRelativeToolRequest_<std::allocator<void> > MoveRelativeToolRequest;

typedef boost::shared_ptr< ::ArmController::MoveRelativeToolRequest > MoveRelativeToolRequestPtr;
typedef boost::shared_ptr< ::ArmController::MoveRelativeToolRequest const> MoveRelativeToolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ArmController

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cebd33aacfc803188fa479cfc00240bc";
  }

  static const char* value(const ::ArmController::MoveRelativeToolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcebd33aacfc80318ULL;
  static const uint64_t static_value2 = 0x8fa479cfc00240bcULL;
};

template<class ContainerAllocator>
struct DataType< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmController/MoveRelativeToolRequest";
  }

  static const char* value(const ::ArmController::MoveRelativeToolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tx\n\
int32 ty\n\
int32 tz\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const ::ArmController::MoveRelativeToolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tx);
      stream.next(m.ty);
      stream.next(m.tz);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveRelativeToolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ArmController::MoveRelativeToolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ArmController::MoveRelativeToolRequest_<ContainerAllocator>& v)
  {
    s << indent << "tx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tx);
    s << indent << "ty: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ty);
    s << indent << "tz: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tz);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_MOVERELATIVETOOLREQUEST_H
