// Generated by gencpp from file ArmController/MoveAbsoluteMotorRequest.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTORREQUEST_H
#define ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ArmController
{
template <class ContainerAllocator>
struct MoveAbsoluteMotorRequest_
{
  typedef MoveAbsoluteMotorRequest_<ContainerAllocator> Type;

  MoveAbsoluteMotorRequest_()
    : motorID(0)
    , angle(0.0)  {
    }
  MoveAbsoluteMotorRequest_(const ContainerAllocator& _alloc)
    : motorID(0)
    , angle(0.0)  {
    }



   typedef int8_t _motorID_type;
  _motorID_type motorID;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveAbsoluteMotorRequest_

typedef ::ArmController::MoveAbsoluteMotorRequest_<std::allocator<void> > MoveAbsoluteMotorRequest;

typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorRequest > MoveAbsoluteMotorRequestPtr;
typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorRequest const> MoveAbsoluteMotorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ArmController

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52ffe69d55b4b8197d25cc69b97f4c61";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52ffe69d55b4b819ULL;
  static const uint64_t static_value2 = 0x7d25cc69b97f4c61ULL;
};

template<class ContainerAllocator>
struct DataType< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmController/MoveAbsoluteMotorRequest";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 motorID\n\
float32 angle\n\
";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorID);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveAbsoluteMotorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ArmController::MoveAbsoluteMotorRequest_<ContainerAllocator>& v)
  {
    s << indent << "motorID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.motorID);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTORREQUEST_H
