// Generated by gencpp from file ArmController/MoveRelativeTool.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_MOVERELATIVETOOL_H
#define ARMCONTROLLER_MESSAGE_MOVERELATIVETOOL_H

#include <ros/service_traits.h>


#include <ArmController/MoveRelativeToolRequest.h>
#include <ArmController/MoveRelativeToolResponse.h>


namespace ArmController
{

struct MoveRelativeTool
{

typedef MoveRelativeToolRequest Request;
typedef MoveRelativeToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRelativeTool
} // namespace ArmController


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ArmController::MoveRelativeTool > {
  static const char* value()
  {
    return "cebd33aacfc803188fa479cfc00240bc";
  }

  static const char* value(const ::ArmController::MoveRelativeTool&) { return value(); }
};

template<>
struct DataType< ::ArmController::MoveRelativeTool > {
  static const char* value()
  {
    return "ArmController/MoveRelativeTool";
  }

  static const char* value(const ::ArmController::MoveRelativeTool&) { return value(); }
};


// service_traits::MD5Sum< ::ArmController::MoveRelativeToolRequest> should match 
// service_traits::MD5Sum< ::ArmController::MoveRelativeTool > 
template<>
struct MD5Sum< ::ArmController::MoveRelativeToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::MoveRelativeTool >::value();
  }
  static const char* value(const ::ArmController::MoveRelativeToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::MoveRelativeToolRequest> should match 
// service_traits::DataType< ::ArmController::MoveRelativeTool > 
template<>
struct DataType< ::ArmController::MoveRelativeToolRequest>
{
  static const char* value()
  {
    return DataType< ::ArmController::MoveRelativeTool >::value();
  }
  static const char* value(const ::ArmController::MoveRelativeToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ArmController::MoveRelativeToolResponse> should match 
// service_traits::MD5Sum< ::ArmController::MoveRelativeTool > 
template<>
struct MD5Sum< ::ArmController::MoveRelativeToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::MoveRelativeTool >::value();
  }
  static const char* value(const ::ArmController::MoveRelativeToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::MoveRelativeToolResponse> should match 
// service_traits::DataType< ::ArmController::MoveRelativeTool > 
template<>
struct DataType< ::ArmController::MoveRelativeToolResponse>
{
  static const char* value()
  {
    return DataType< ::ArmController::MoveRelativeTool >::value();
  }
  static const char* value(const ::ArmController::MoveRelativeToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_MOVERELATIVETOOL_H
