// Generated by gencpp from file ArmController/MoveAbsoluteMotor.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTOR_H
#define ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTOR_H

#include <ros/service_traits.h>


#include <ArmController/MoveAbsoluteMotorRequest.h>
#include <ArmController/MoveAbsoluteMotorResponse.h>


namespace ArmController
{

struct MoveAbsoluteMotor
{

typedef MoveAbsoluteMotorRequest Request;
typedef MoveAbsoluteMotorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveAbsoluteMotor
} // namespace ArmController


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ArmController::MoveAbsoluteMotor > {
  static const char* value()
  {
    return "52ffe69d55b4b8197d25cc69b97f4c61";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotor&) { return value(); }
};

template<>
struct DataType< ::ArmController::MoveAbsoluteMotor > {
  static const char* value()
  {
    return "ArmController/MoveAbsoluteMotor";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotor&) { return value(); }
};


// service_traits::MD5Sum< ::ArmController::MoveAbsoluteMotorRequest> should match 
// service_traits::MD5Sum< ::ArmController::MoveAbsoluteMotor > 
template<>
struct MD5Sum< ::ArmController::MoveAbsoluteMotorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::MoveAbsoluteMotor >::value();
  }
  static const char* value(const ::ArmController::MoveAbsoluteMotorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::MoveAbsoluteMotorRequest> should match 
// service_traits::DataType< ::ArmController::MoveAbsoluteMotor > 
template<>
struct DataType< ::ArmController::MoveAbsoluteMotorRequest>
{
  static const char* value()
  {
    return DataType< ::ArmController::MoveAbsoluteMotor >::value();
  }
  static const char* value(const ::ArmController::MoveAbsoluteMotorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ArmController::MoveAbsoluteMotorResponse> should match 
// service_traits::MD5Sum< ::ArmController::MoveAbsoluteMotor > 
template<>
struct MD5Sum< ::ArmController::MoveAbsoluteMotorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ArmController::MoveAbsoluteMotor >::value();
  }
  static const char* value(const ::ArmController::MoveAbsoluteMotorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ArmController::MoveAbsoluteMotorResponse> should match 
// service_traits::DataType< ::ArmController::MoveAbsoluteMotor > 
template<>
struct DataType< ::ArmController::MoveAbsoluteMotorResponse>
{
  static const char* value()
  {
    return DataType< ::ArmController::MoveAbsoluteMotor >::value();
  }
  static const char* value(const ::ArmController::MoveAbsoluteMotorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTOR_H
