// Generated by gencpp from file ArmController/MoveAbsoluteMotorResponse.msg
// DO NOT EDIT!


#ifndef ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTORRESPONSE_H
#define ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ArmController
{
template <class ContainerAllocator>
struct MoveAbsoluteMotorResponse_
{
  typedef MoveAbsoluteMotorResponse_<ContainerAllocator> Type;

  MoveAbsoluteMotorResponse_()
    {
    }
  MoveAbsoluteMotorResponse_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveAbsoluteMotorResponse_

typedef ::ArmController::MoveAbsoluteMotorResponse_<std::allocator<void> > MoveAbsoluteMotorResponse;

typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorResponse > MoveAbsoluteMotorResponsePtr;
typedef boost::shared_ptr< ::ArmController::MoveAbsoluteMotorResponse const> MoveAbsoluteMotorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ArmController

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmController/MoveAbsoluteMotorResponse";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveAbsoluteMotorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ArmController::MoveAbsoluteMotorResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROLLER_MESSAGE_MOVEABSOLUTEMOTORRESPONSE_H
